#!/bin/bash

# Exit on error
set -e

VENV_DIR=".venv"

# Create virtual environment if it doesn't exist
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    echo "Virtual environment created at $VENV_DIR"
fi

# Activate the virtual environment
source "$VENV_DIR/bin/activate"

# Upgrade pip
pip install --upgrade pip

# Install requirements
if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt
    echo "Requirements installed."
else
    echo "requirements.txt not found!"
    exit 1
fi

# Create required folder structure if it doesn't exist
echo "Creating folder strucutre for training and testing data..."
mkdir -p data/train/shark
mkdir -p data/train/no_shark
mkdir -p data/test/shark
mkdir -p data/test/no_shark

# Create logs directory
# mkdir -p logs

# Create models directory
mkdir -p models

# Create video directory
mkdir -p videos

echo "Development environment setup complete."